//Defaut tab
 






























const premier = document.querySelector(".premier");
const deuxieme = document.querySelector(".deuxieme");
const troisieme = document.querySelector(".troisieme");
const button1= document.querySelector('.button1');
const button2= document.querySelector('.button2');
const button3 = document.querySelector('.button3');
const button4 = document.querySelector('.button4');

const step1 = document.querySelector(".step1");
const step2 = document.querySelector(".step2");
const step3 = document.querySelector(".step3");
const step4= document.querySelector('.step4');
const step5= document.querySelector('.step5');
const step6 = document.querySelector('.step6');
const step7 = document.querySelector('.step7');
const step8 = document.querySelector('.step8');
const step9 = document.querySelector('.step9');




button1.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";
    step4.style.display = "flex";
    step5.style.display = "flex";
    step6.style.display = "flex";
 })


button2.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "none";
    troisieme.style.display = "flex";

})

button2.addEventListener("click",() => {
    premier.style.display = "flex";
    deuxieme.style.display = "none";
    troisieme.style.display = "none";

})

button3.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "none";
    troisieme.style.display = "flex";

})

button4.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";

})



// const step1 = document.querySelector(".step1");
// const step2 = document.querySelector(".step2");
// const step3 = document.querySelector(".step3");
// const step4= document.querySelector('.step4');
// const step5= document.querySelector('.step5');
// const step6 = document.querySelector('.step6');
// const step7 = document.querySelector('.step7');
// const step8 = document.querySelector('.step8');
// const step9 = document.querySelector('.step9');



button1.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";
    step4.style.display = "flex";
    step5.style.display = "flex";
    step6.style.display = "flex";
 })

 button3.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "none";
    troisieme.style.display = "flex";
    step7.style.display = "flex";
    step8.style.display = "flex";
    step9.style.display = "flex";
 })


 step2.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";
    step4.style.display = "none";
    step5.style.display = "flex";
    step6.style.display = "none";
 })


 step2.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";
    step4.style.display = "flex";
    step5.style.display = "flex";
    step6.style.display = "flex";
 })



 step6.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "none";
    troisieme.style.display = "flex";
    step7.style.display = "flex";
    step8.style.display = "flex";
    step9.style.display = "flex";
 })


 step8.addEventListener("click",() => {
    premier.style.display = "none";
    deuxieme.style.display = "flex";
    troisieme.style.display = "none";
    step4.style.display = "flex";
    step5.style.display = "flex";
    step6.style.display = "flex";
 })

 step4.addEventListener("click",() => {
    premier.style.display = "flex";
    deuxieme.style.display = "none";
    troisieme.style.display = "none";
    step1.style.display = "flex";
    step2.style.display = "flex";
    step3.style.display = "flex";
 })










